### ISSUE TITLE
你好，CFR模型在哪里可以看到？

### ISSUE THREAD

**Issue by xmgfx** [deecamp2019-group20/DC2019-ddz#2]
你好，CFR模型在哪里可以看到？看新闻里面你们写道这个算法很好，有开源吗？

**Comment by Legend94rz** [comment]
很遗憾，我们的没有开源。不过有其他人的实现供参考：https://github.com/EricSteinberger/PokerRL

**Comment by xmgfx** [comment]
谢谢回复，你们有发相关论文计划吗？
另外可否请教下，看新闻里描述你们做了5个模型，你们做的模型里面那个总体胜率最高，是CFR模型么？5个模型有具体比较么？
